#+TITLE:  My Global Key Bindings
#+AUTHOR: JJ Asghar
#+EMAIL:  jjasghar@gmail.com

* General

These are some globalkey bindings I've gotten used to or want to have. I bet they are redundant, but at least I can think of them
without needing to to =M-x blah=.

* Web key bindings

** browse-url
I like the idea of being able to hit =C-c b= on a URL and have it open in my browser.

#+begin_src emacs-lisp :tangle yes
(global-set-key (kbd "C-c b") 'browse-url-at-point)
#+end_src

* Local Computer key bindings
** dash-at-point
I use dash pretty regulary on a Mac, this way I can look something up with a keystroke.

#+begin_src emacs-lisp :tangle yes
(global-set-key "\C-cd" 'dash-at-point)
#+end_src

** Spell check
I can never seem to remember what the spell check is, but =M-s M-s= seemed quick enough for me.

#+begin_src emacs-lisp :tangle yes
(global-set-key (kbd "M-s M-s") 'ispell-word)
#+end_src

** [Comment|Uncomment] region
While I'm debugging the best think I can do is Comment out or Uncomment out quickly to figure out what's going wrong.

#+begin_src emacs-lisp :tangle yes
(global-set-key "\C-c#" 'comment-region)
(global-set-key "\C-cu" 'uncomment-region)
#+end_src

** indent-region
This just seemed like a logical key binding. I almost never use it though.
#+begin_src emacs-lisp :tangle yes
(global-set-key "\C-ci" 'indent-region)
#+end_src

**  text size
It's nice to be able to make the text size bigger and smaller. On a Mac it's =Command-+= so this seemed logical.

#+begin_src emacs-lisp :tangle yes
(global-set-key "\M-+" 'text-scale-increase)
(global-set-key "\M-_" 'text-scale-decrease)
#+end_src

** ace-jump-mode
Something I wish I used more. Adam Spiers showed this trick to me; I just need to use it more.

#+begin_src emacs-lisp :tangle yes
(global-set-key (kbd "C-0") 'ace-jump-char-mode)
#+end_src

** write-out-region
Sometimes I have a region that could it's own file. This does it for me.

#+begin_src emacs-lisp :tangle yes
(global-set-key (kbd "C-x w") 'write-region)
#+end_src

** magit-status
Per the magit readme, this is one of the most used key bindings I have.

#+begin_src emacs-lisp :tangle yes
(global-set-key (kbd "C-c g") 'magit-status)
#+end_src

** shortcut for shell
I sometimes don't want to hop over to my Terminal, this way I can do it inside of emacs.

#+begin_src emacs-lisp :tangle yes
(global-set-key (kbd "C-c s") 'shell)
#+end_src

** toggle horizontal and vertial splits
I like splitting frames, this way i can flip em.

#+begin_src emacs-lisp :tangle yes
(global-set-key (kbd "C-x |") 'toggle-window-split)
#+end_src
